### ISSUE TITLE
【ReferenceError: done is not defined】

### ISSUE THREAD

**Issue by sgdream** [qfdk/EasyDockerWeb#7]
I pull `EasyDockerWeb` from `docker.io/qfdk/easydockerweb`
```
docker pull qfdk/easydockerweb
```
then RUN IT
```
 docker run -it -d -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock qfdk/easydockerweb
```
Everything is fine, until I `Pull image`

It Exited
### logs：

docker logs EasyDockerWeb
```
Listening on port 3000
/src/routes/images.js:63
          if (err) return done(err);
                   ^

ReferenceError: done is not defined
    at onFinished (/src/routes/images.js:63:20)
    at onStreamError (/src/node_modules/docker-modem/lib/modem.js:338:5)
    at Stream.onStreamEvent (/src/node_modules/docker-modem/lib/modem.js:326:14)
    at Stream.emit (events.js:180:13)
    at drain (/src/node_modules/through/index.js:36:16)
    at Stream.stream.queue.stream.push (/src/node_modules/through/index.js:45:5)
    at Parser.parser.onToken (/src/node_modules/JSONStream/index.js:130:18)
    at Parser.proto.write (/src/node_modules/jsonparse/jsonparse.js:135:34)
    at Stream.<anonymous> (/src/node_modules/JSONStream/index.js:21:12)
    at Stream.stream.write (/src/node_modules/through/index.js:26:11)
```

**Comment by qfdk** [comment]
Hello @sgdream, 

You could pull the code and run the commande:
 
```bash
git clone https://github.com/qfdk/EasyDockerWeb.git
cd EasyDockerWeb
docker build -t easy-docker-web .
docker run -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock easy-docker-web
```

The code in docker hub is not the lastest version. I will fix it.

Best W

**Comment by qfdk** [comment]
@sgdream The problem was fixed. The image which you want to pull must be proposed by auto completion system.

**Comment by qfdk** [comment]
Done

**Comment by sgdream** [comment]
Thanks :)
