### ISSUE TITLE
SyntaxError: Unexpected identifier 'include'

### ISSUE THREAD

**Issue by Aerya** [qfdk/EasyDockerWeb#73]
Hi,

Pushed qfdk/easydockerweb and got this error:
```
SyntaxError: Unexpected identifier 'include' in /src/views/error.html while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
Or, if you meant to create an async function, pass `async: true` as an option.
    at new Function (<anonymous>)
    at Template.compile (/src/node_modules/ejs/lib/ejs.js:673:12)
    at Object.compile (/src/node_modules/ejs/lib/ejs.js:398:16)
    at handleCache (/src/node_modules/ejs/lib/ejs.js:235:18)
    at tryHandleCache (/src/node_modules/ejs/lib/ejs.js:274:16)
    at exports.renderFile [as engine] (/src/node_modules/ejs/lib/ejs.js:491:10)
    at View.render (/src/node_modules/express/lib/view.js:135:8)
    at tryRender (/src/node_modules/express/lib/application.js:657:10)
    at Function.render (/src/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/src/node_modules/express/lib/response.js:1039:7)
```

Thanks

**Comment by qfdk** [comment]
Hello, @Aerya  

I have fixed that in the commit https://github.com/qfdk/EasyDockerWeb/commit/f012bdee15a1dc6c042ca08d2691d641a8563d23, because the update library ejs.

Thanks
